// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEYB6guyz-uT8Mhwf4Lkaoe-ZLBr2p0aY',
    appId: '1:632730996258:ios:33865d097c3f4a2be5447b',
    messagingSenderId: '632730996258',
    projectId: 'zonifypro',
    storageBucket: 'zonifypro.firebasestorage.app',
    iosBundleId: 'com.example.zonifypro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEYB6guyz-uT8Mhwf4Lkaoe-ZLBr2p0aY',
    appId: '1:632730996258:ios:33865d097c3f4a2be5447b',
    messagingSenderId: '632730996258',
    projectId: 'zonifypro',
    storageBucket: 'zonifypro.firebasestorage.app',
    iosBundleId: 'com.example.zonifypro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA34Cmb_ccydX88DLle1AbZmadpcNJAhI',
    appId: '1:632730996258:web:5a8d8ae5f852911be5447b',
    messagingSenderId: '632730996258',
    projectId: 'zonifypro',
    authDomain: 'zonifypro.firebaseapp.com',
    storageBucket: 'zonifypro.firebasestorage.app',
    measurementId: 'G-T8V7HX30FR',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA34Cmb_ccydX88DLle1AbZmadpcNJAhI',
    appId: '1:632730996258:web:48623c28c85156e4e5447b',
    messagingSenderId: '632730996258',
    projectId: 'zonifypro',
    authDomain: 'zonifypro.firebaseapp.com',
    storageBucket: 'zonifypro.firebasestorage.app',
    measurementId: 'G-TY532GBWKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8i5xjuKmQowJXsXHXBTPsf007v7IwahE',
    appId: '1:632730996258:android:c97c058ede5cff46e5447b',
    messagingSenderId: '632730996258',
    projectId: 'zonifypro',
    storageBucket: 'zonifypro.firebasestorage.app',
  );

}